#Database spec
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reportsdb
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true