#Database spec
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reportsdb
    username: reportsdb
    password: reportsdb
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
